name: Python Tests

on:
  push:
    branches: [ main ] # Oder deine Hauptbranch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Betriebssystem des Runners
    container:
      image: python:3.9-slim

    steps:
    - uses: actions/checkout@v3 # Repository auschecken
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Installiere Abhängigkeiten aus requirements.txt
        pip install pytest # pytest installieren
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi # optionale dev-abhängigkeiten
    - name: Test with pytest
      run: pytest